import type { Product } from './types/product'

export const productData: Product[] = [
  {
    id: '1',
    name: 'Camiseta Casual',
    description: 'Camiseta de algodón de alta calidad con diseño moderno',
    price: 29.99,
    category: 'Ropa',
    image: '/placeholder.svg?height=300&width=300',
    inStock: true,
  },
  {
    id: '2',
    name: 'Zapatillas Deportivas',
    description: 'Zapatillas cómodas para correr o entrenar',
    price: 89.99,
    category: 'Calzado',
    image: '/placeholder.svg?height=300&width=300',
    inStock: true,
  },
  {
    id: '3',
    name: 'Reloj Inteligente',
    description: 'Smartwatch con múltiples funciones y batería de larga duración',
    price: 149.99,
    category: 'Electrónica',
    image: '/placeholder.svg?height=300&width=300',
    inStock: true,
  },
  {
    id: '4',
    name: 'Auriculares Bluetooth',
    description: 'Auriculares inalámbricos con cancelación de ruido',
    price: 79.99,
    category: 'Electrónica',
    image: '/placeholder.svg?height=300&width=300',
    inStock: false,
  },
  {
    id: '5',
    name: 'Pantalones Vaqueros',
    description: 'Jeans de corte recto y material duradero',
    price: 49.99,
    category: 'Ropa',
    image: '/placeholder.svg?height=300&width=300',
    inStock: true,
  },
  {
    id: '6',
    name: 'Bolso de Cuero',
    description: 'Bolso elegante de cuero genuino con múltiples compartimentos',
    price: 119.99,
    category: 'Accesorios',
    image: '/placeholder.svg?height=300&width=300',
    inStock: true,
  },
  {
    id: '7',
    name: 'Gafas de Sol',
    description: 'Gafas de sol con protección UV y diseño moderno',
    price: 39.99,
    category: 'Accesorios',
    image: '/placeholder.svg?height=300&width=300',
    inStock: true,
  },
  {
    id: '8',
    name: 'Chaqueta de Invierno',
    description: 'Chaqueta térmica resistente al agua para climas fríos',
    price: 129.99,
    category: 'Ropa',
    image: '/placeholder.svg?height=300&width=300',
    inStock: false,
  },
  {
    id: '9',
    name: 'Tablet 10 pulgadas',
    description: 'Tablet con pantalla HD y procesador rápido',
    price: 199.99,
    category: 'Electrónica',
    image: '/placeholder.svg?height=300&width=300',
    inStock: true,
  },
]

export const categories = [
  { value: 'Ropa', label: 'Ropa' },
  { value: 'Calzado', label: 'Calzado' },
  { value: 'Electrónica', label: 'Electrónica' },
  { value: 'Accesorios', label: 'Accesorios' },
]
